=== juanluss31/SAT-UJA/Ejercicios/2/gestor.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tarea">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" />
                <xs:element name="fechainicio" type="xs:date" />
                <xs:element name="duracionmaxima" type="xs:integer" />
                <xs:element name="recursos" type="propiedadesrecurso" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="procesos" type="propiedadesproceso" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="propiedadesrecurso">
        <xs:sequence>
            <xs:element name="idequipo" type="xs:string" />
            <xs:element name="memoria" type="xs:integer" />
            <xs:element name="idprocesador" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="propiedadesproceso">
        <xs:sequence>
            <xs:element name="idproceso" type="xs:string" />
            <xs:element name="descripcion" type="xs:string" />
            <xs:element name="nombreproceso" type="xs:string" />
            <xs:element name="permisos" type="xs:string" />
            <xs:element name="cancelable" type="xs:boolean" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== juanluss31/SAT-UJA/Ejercicios/2/ejemplo.xml
<?xml version="1.0" encoding="utf-8"?>

<tarea xsi:noNamespaceSchemaLocation="gestor.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <nombre>Nombre de la tarea</nombre>
    <fechainicio>2022-03-31</fechainicio>
    <duracionmaxima>30</duracionmaxima>
    <recursos>
        <idequipo>equipo1</idequipo>
        <memoria>-4409</memoria>
        <idprocesador>HAD5F26A</idprocesador>
    </recursos>
    <recursos>
        <idequipo>equipo2</idequipo>
        <memoria>2983</memoria>
        <idprocesador>HAD2G34B</idprocesador>
    </recursos>
    <procesos>
        <idproceso>proceso1</idproceso>
        <descripcion>Descripción del proceso 1</descripcion>
        <nombreproceso>Nombre del proceso 1</nombreproceso>
        <permisos>Leer y escribir</permisos>
        <cancelable>0</cancelable>
    </procesos>
    <procesos>
        <idproceso>proceso2</idproceso>
        <descripcion>Descripción del proceso 1</descripcion>
        <nombreproceso>Nombre del proceso 2</nombreproceso>
        <permisos>Sólo lectura</permisos>
        <cancelable>1</cancelable>
    </procesos>
</tarea>
